# Generated by Django 4.2.6 on 2024-04-23 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0002_alter_post_post_photo_alter_post_profile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_video',
            field=models.BooleanField(default=False),
        ),
    ]
